### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by Gouiaa** [facebookresearch/DensePose#150]
I can not pass the `make ops` test. here is the error

mkdir -p build && cd build && cmake .. && make -j12 -DCUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/libcudart.so
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /home/xxx/anaconda3/envs/densepose/bin/cc
-- Check for working C compiler: /home/xxx/anaconda3/envs/densepose/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/xxx/anaconda3/envs/densepose/bin/c++
-- Check for working CXX compiler: /home/xxx/anaconda3/envs/densepose/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Could NOT find CUDA (missing: CUDA_CUDART_LIBRARY) (found suitable version "9.1", minimum required is "7.0")
CMake Warning at /home/xxx/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:10 (message):
  Caffe2: CUDA cannot be found.  Depending on whether you are building Caffe2
  or a Caffe2 dependent library, the next warning / error will give you more
  info.
Call Stack (most recent call first):
  /home/xxx/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  CMakeLists.txt:8 (find_package)

CMake Error at /home/xxx/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:90 (message):
  Your installed Caffe2 version uses CUDA but I cannot find the CUDA
  libraries.  Please set the proper CUDA prefixes and / or install CUDA.
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)

**Comment by linkinpark213** [comment]
I thinks I met with this problem earlier. In my case, `context.h` wasn't in `caffe2/core/` but in other directories (I wonder why, too). Solved by adding this line to CMakeLists.txt:

    include_directories("/path/to/pytorch/torch/lib/include")

If it doesn't help, try finding your own `context.h` in your Caffe2 path, and replace the path above with it.

**Comment by Gouiaa** [comment]
@linkinpark213 Thanks. I fixed this error but getting an other.
I add these line in `CmakeLists.txt` file
set(CMAKE_PREFIX_PATH "/home/rafikg/anaconda3/envs/facebook/lib/python2.7/site-packages/torch/share/cmake/Caffe2")
set(CUDNN_INCLUDE_DIR "/usr/local/cuda/include")
set(CUDNN_LIBRARY "/usr/local/cuda/lib64/libcudart.so")
include_directories("/home/rafikg/anaconda3/envs/facebook/lib/python2.7/site-packages/torch/lib/include" "/home/rafikg/anaconda3/envs/facebook/include")

**In file included from /home/rafikg/anaconda3/envs/facebook/lib/python2.7/site-packages/torch/lib/include/caffe2/core/context_gpu.h:8:0,
                 from /home/rafikg/Documents/Bitbucket/Detectron/detectron/ops/zero_even_op.cu:17:
/home/rafikg/anaconda3/envs/facebook/lib/python2.7/site-packages/torch/lib/include/caffe2/core/common_gpu.h:28:37: fatal error: c10/cuda/CUDAMathCompat.h: No such file or directory
compilation terminated.**

I can not find the `cuda` folder under  `/anaconda3/envs/facebook/lib/python2.7/site-packages/torch/lib/include/c10`
Did you get this error ?
I get also an other error may be it is in relation with the other 
**/home/rafikg/anaconda3/envs/facebook/lib/python2.7/site-packages/torch/lib/include/caffe2/utils/cblas.h:8:10: fatal error: mkl_cblas.h: No such file or directory
 #include <mkl_cblas.h>**
This code makes all people crazy :(

**Comment by linkinpark213** [comment]
> @linkinpark213 Thanks. I fixed this error but getting an other.
> I add these line in `CmakeLists.txt` file
> set(CMAKE_PREFIX_PATH "/home/rafikg/anaconda3/envs/facebook/lib/python2.7/site-packages/torch/share/cmake/Caffe2")
> set(CUDNN_INCLUDE_DIR "/usr/local/cuda/include")
> set(CUDNN_LIBRARY "/usr/local/cuda/lib64/libcudart.so")
> include_directories("/home/rafikg/anaconda3/envs/facebook/lib/python2.7/site-packages/torch/lib/include" "/home/rafikg/anaconda3/envs/facebook/include")
> 
> I get an other error:
> 
> **/home/rafikg/anaconda3/envs/facebook/lib/python2.7/site-packages/torch/lib/include/caffe2/utils/cblas.h:8:10: fatal error: mkl_cblas.h: No such file or directory #include <mkl_cblas.h>**
> This code makes all people crazy :(

I met with this problem, too. Some variable named like USE_MKL or so was set to be ON but it wasn't installed. Therefore, I installed [MKL](https://software.intel.com/en-us/mkl/choose-download/linux) and added its include path to CPATH. In my case it was:

    export CPATH=$CPATH:/opt/intel/compilers_and_libraries_2019.1.144/linux/mkl/include

the exact path may vary according to the version of MKL and your configuration.

**Comment by Gouiaa** [comment]
Thanks for your reply. I resolved almost problem. Still having `undefined symbol: _ZN6google8protobuf8internal10LogMessagelsEPKc` even when I apply these instructions [http://linkinpark213.com/2018/11/18/densepose-minesweeping/#2-7-Undefined-symbol-ZN6google8protobuf8internal9ArenaImpl28AllocateAlignedAndAddCleanupEmPFvPvE](url) and another error when running simple_infer  [https://github.com/facebookresearch/DensePose/issues/33](url)

**Comment by linkinpark213** [comment]
> Thanks for your reply. I resolved almost problem. Still having `undefined symbol: _ZN6google8protobuf8internal10LogMessagelsEPKc` even when I apply these instructions [http://linkinpark213.com/2018/11/18/densepose-minesweeping/#2-7-Undefined-symbol-ZN6google8protobuf8internal9ArenaImpl28AllocateAlignedAndAddCleanupEmPFvPvE](url) and another error when running simple_infer [https://github.com/facebookresearch/DensePose/issues/33](url)

Emmmm, you didn't forget about running `make ops` again, did you?

It was my carelessness not to notice that you installed Caffe2 with Anaconda. My Caffe2 had a `protobuf` submodule which was an older commit [#2761122b](https://github.com/protocolbuffers/protobuf/tree/2761122b810fe8861004ae785cc3ab39f384d342), pushed on November 14th, 2017. I searched [protobuf releases page](https://github.com/protocolbuffers/protobuf/releases) and found out that the version number should be v3.5.0. Therefore, if you set `PROTOBUF_LIB` to your `protobuf.a` which was installed with Anaconda, I guess you'll need to make it v3.5.0.

As for the other issue, I have no idea yet. Maybe try the others' solutions?

**Comment by Gouiaa** [comment]
@linkinpark213 Sure, I run `make ops` and installed protobuf=3.5.0 and still having the same error

**Comment by linkinpark213** [comment]
@Gouiaa I'm suppose that there are some clashes among multiple protobufs. Did you install other versions of protobuf with `apt-get` or `pip`?

**Comment by ckyleda** [comment]
I have this EXACT same issue with only one version of protobuf (3.5.0) installed.

@linkinpark213 

There are no other versions of the protobuf library installed.

What is going on here? Is this even possible to fix? I've tried every posted solution and nothing works - it's like there's some hidden protobuf dependency that pytorch uses.

There is no protobuf library packaged with the anaconda install of pytorch( which obviously there should be) and inspecting the caffe libraries with ldd reveal on dependency on libprotobuf at all!

What are the densepose devs playing at?

**Comment by linkinpark213** [comment]
Please calm down. As you mentioned,
> I have this EXACT same issue with only one version of protobuf (3.5.0) installed.

Did you mean `OSError: .../build/libcaffe2_detectron_custom_ops_gpu.so: undefined symbol: _ZN6google8protobuf8internal9ArenaImpl28AllocateAlignedAndAddCleanupEmPFvPvE`?

If so, @Gouiaa and I solved this issue with PyTorch built from source. The source code includes the [Detectron module](https://github.com/pytorch/pytorch/tree/master/modules/detectron) and third party dependencies (also `protobuf`, even now), while the anaconda installation doesn't. Therefore, you may have to [build PyTorch](https://github.com/pytorch/pytorch#from-source) by yourself.

I strongly agree that the developers should work on how to make the installation procedure less painful, though.

**Comment by ckyleda** [comment]
Building PyTorch from source is intractable as that repository is also broken.

It seems that none of these projects actually work.

**Comment by ckyleda** [comment]
I have now built PyTorch and confirmed caffe2 working, and referenced the built libprotobuf (from pytorch) in the CMakeLists file and rebuilt (make ops) and can confirm that this does not resolve the issue.

libcaffe2_detectron_custom_ops_gpu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

Is there any other way to move forward?

**Comment by ckyleda** [comment]
@Gouiaa @linkinpark213 

I have now resolved this.
For future reference:

If you have followed instructions to get the Anaconda version of Pytorch working with Densepose, then switch to the built version, you must remove the additional line in the CMakeLists file that added the source files to resolve the 'ThreadPool.h missing' error as shown in:

https://linkinpark213.com/2018/11/18/densepose-minesweeping/#2-8-fatal-error-caffe2-utils-threadpool-ThreadPool-h-No-such-file-or-directory

This was a ridiculous journey.

Thanks to @linkinpark213 for his comprehensive blog and github posts.

@Gouiaa I agree that this kind of installation process is insane. Nearly nothing works out of the box and the standard supplied guide is essentially useless.

Unfortunately I'm not sure how to help you achieve a better framerate - is your GPU definitely being utilised?
