### ISSUE TITLE
make ops

### ISSUE THREAD

**Issue by shen113** [facebookresearch/DensePose#205]
Can somebody help me? My protoc version is 3.5.0, but it still can't work

mkdir -p build && cd build && cmake .. && make -j8
-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda-9.0/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-9.0
-- Caffe2: Header version is: 9.0
-- Found cuDNN: v7.1.4  (include: /usr/local/cuda-9.0/include, library: /usr/local/cuda-9.0/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s): 5.2
-- Added CUDA NVCC flags for: -gencode;arch=compute_52,code=sm_52
-- Summary:
--   CMake version        : 3.13.3
--   CMake command        : /usr/local/bin/cmake
--   System name          : Linux
--   C++ compiler         : /usr/bin/c++
--   C++ compiler version : 4.9.3
--   CXX flags            :  -std=c++11 -O2 -fPIC -Wno-narrowing
--   Caffe2 version       : 1.0.0
--   Caffe2 include path  : /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include
--   Caffe2 found CUDA    : True
--     CUDA version       : 9.0
--     CuDNN version      : 7.1.4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mclab/anaconda2/envs/try/clone/densepose/build
make[1]: Entering directory '/home/mclab/anaconda2/envs/try/clone/densepose/build'
make[2]: Entering directory '/home/mclab/anaconda2/envs/try/clone/densepose/build'
make[3]: Entering directory '/home/mclab/anaconda2/envs/try/clone/densepose/build'
make[3]: Entering directory '/home/mclab/anaconda2/envs/try/clone/densepose/build'
[ 12%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o
[ 25%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o
make[3]: Leaving directory '/home/mclab/anaconda2/envs/try/clone/densepose/build'
make[3]: Entering directory '/home/mclab/anaconda2/envs/try/clone/densepose/build'
[ 37%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o
[ 50%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o
In file included from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2_pb.h:4:0,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context_base.h:7,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context.h:10,
                 from /home/mclab/anaconda2/envs/try/clone/densepose/detectron/ops/zero_even_op.h:12,
                 from /home/mclab/anaconda2/envs/try/clone/densepose/detectron/ops/zero_even_op.cc:9:
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2_pb.h:4:0,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context_base.h:7,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context.h:10,
                 from /home/mclab/anaconda2/envs/try/clone/densepose/detectron/ops/pool_points_interp.h:13,
                 from /home/mclab/anaconda2/envs/try/clone/densepose/detectron/ops/pool_points_interp.cc:10:
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2_pb.h:4:0,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context_base.h:7,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context.h:10,
                 from /home/mclab/anaconda2/envs/try/clone/densepose/detectron/ops/zero_even_op.h:12,
                 from /home/mclab/anaconda2/envs/try/clone/densepose/detectron/ops/zero_even_op.cc:9:
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:27:50: fatal error: google/protobuf/inlined_string_field.h: 沒有此一檔案或目錄
 #include <google/protobuf/inlined_string_field.h>
                                                  ^
compilation terminated.
In file included from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2_pb.h:4:0,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context_base.h:7,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context.h:10,
                 from /home/mclab/anaconda2/envs/try/clone/densepose/detectron/ops/pool_points_interp.h:13,
                 from /home/mclab/anaconda2/envs/try/clone/densepose/detectron/ops/pool_points_interp.cc:10:
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:27:50: fatal error: google/protobuf/inlined_string_field.h: 沒有此一檔案或目錄
 #include <google/protobuf/inlined_string_field.h>
                                                  ^
compilation terminated.
In file included from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2_pb.h:4:0,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context_base.h:7,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context.h:10,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context_gpu.h:9,
                 from /home/mclab/anaconda2/envs/try/clone/densepose/detectron/ops/pool_points_interp.cu:11:
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2_pb.h:4:0,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context_base.h:7,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context.h:10,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context_gpu.h:9,
                 from /home/mclab/anaconda2/envs/try/clone/densepose/detectron/ops/zero_even_op.cu:9:
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2_pb.h:4:0,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context_base.h:7,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context.h:10,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context_gpu.h:9,
                 from /home/mclab/anaconda2/envs/try/clone/densepose/detectron/ops/pool_points_interp.cu:11:
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:27:50: fatal error: google/protobuf/inlined_string_field.h: 沒有此一檔案或目錄
 #include <google/protobuf/inlined_string_field.h>
                                                  ^
compilation terminated.
In file included from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2_pb.h:4:0,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context_base.h:7,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context.h:10,
                 from /home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/core/context_gpu.h:9,
                 from /home/mclab/anaconda2/envs/try/clone/densepose/detectron/ops/zero_even_op.cu:9:
/home/mclab/anaconda2/envs/try/lib/python2.7/site-packages/torch/include/caffe2/proto/caffe2.pb.h:27:50: fatal error: google/protobuf/inlined_string_field.h: 沒有此一檔案或目錄
 #include <google/protobuf/inlined_string_field.h>
                                                  ^
compilation terminated.
CMake Error at caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o.cmake:219 (message):
  Error generating
  /home/mclab/anaconda2/envs/try/clone/densepose/build/CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/./caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o

CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/build.make:70: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o' failed
make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o] Error 1
make[3]: *** Waiting for unfinished jobs....
CMake Error at caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o.cmake:219 (message):
  Error generating
  /home/mclab/anaconda2/envs/try/clone/densepose/build/CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/./caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o

CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/build.make:63: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o' failed
make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o] Error 1
make[3]: Leaving directory '/home/mclab/anaconda2/envs/try/clone/densepose/build'
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/caffe2_detectron_custom_ops.dir/build.make:75: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o' failed
make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
CMakeFiles/caffe2_detectron_custom_ops.dir/build.make:62: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o' failed
make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o] Error 1
make[3]: Leaving directory '/home/mclab/anaconda2/envs/try/clone/densepose/build'
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/all] Error 2
make[2]: Leaving directory '/home/mclab/anaconda2/envs/try/clone/densepose/build'
Makefile:129: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/mclab/anaconda2/envs/try/clone/densepose/build'
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 2

**Comment by vkhalidov** [comment]
@shen113 you should check whether several versions of protocol buffers coexist on your system and make sure you use the right headers.

**Comment by shen113** [comment]
@vkhalidov  thank you for your answer, but which protoc is the right one and how can i change to the right one?

**Comment by tugstugi** [comment]
@shen113 
maybe remove the system one with apt-get? Try also to install into a clean Anaconda installation.

I made a DensePose Colab notebook, you can repeat the commands on your local computer: https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/DensePose.ipynb

**Comment by shen113** [comment]
Thank you for your reply, I have solved it.

**Comment by guohaoyu110** [comment]
@shen113  Hey, how do you solve it? I come across the same problem

**Comment by tugstugi** [comment]
@guohaoyu110 solution is here: https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/DensePose.ipynb

**Comment by Mutahharahmad97** [comment]
@tugstugi can you please do this for this one too? 
https://github.com/menandro2015git/densepose-webcam
