### ISSUE TITLE
Strange error when running simple_infer.py, can not figure out what is wrong (CuDNN?)

### ISSUE THREAD

**Issue by Tetsujinfr** [facebookresearch/DensePose#43]
I am under Ubuntu 16.04, Cuda 8.0 CuDNN 6.0.21; on a GTX 980Ti. I attach my caffe2 cmake summary and my compile log for ref 
[compile_pytorch.txt](https://github.com/facebookresearch/DensePose/files/2156827/compile_pytorch.txt)
[cmake_pytorch.txt](https://github.com/facebookresearch/DensePose/files/2156828/cmake_pytorch.txt)

Cannot figure out where is the problem. HELP please!!!

 
I pass the first caffe2 tests:
1) python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
Success
2) python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'
1

Then I "fail" the relu_op_test.py with a weird message but I have read those errors may just be warnings so not sure. 

```
 python caffe2/python/operator_test/relu_op_test.py
No handlers could be found for logger "caffe2.python.net_drawer"
net_drawer will not run correctly. Please install the correct dependencies.
/usr/local/lib/python2.7/dist-packages/caffe2/python/hypothesis_test_util.py:75: HypothesisDeprecationWarning: 
The min_satisfying_examples setting has been deprecated and disabled, due to
overlap with the filter_too_much healthcheck and poor interaction with the
max_examples setting.

  verbosity=hypothesis.Verbosity.verbose))
/usr/local/lib/python2.7/dist-packages/caffe2/python/hypothesis_test_util.py:84: HypothesisDeprecationWarning: 
The min_satisfying_examples setting has been deprecated and disabled, due to
overlap with the filter_too_much healthcheck and poor interaction with the
max_examples setting.

  verbosity=hypothesis.Verbosity.verbose))
/usr/local/lib/python2.7/dist-packages/caffe2/python/hypothesis_test_util.py:92: HypothesisDeprecationWarning: 
The min_satisfying_examples setting has been deprecated and disabled, due to
overlap with the filter_too_much healthcheck and poor interaction with the
max_examples setting.

  verbosity=hypothesis.Verbosity.verbose))
E0702 22:04:28.531708  3503 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0702 22:04:28.531721  3503 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0702 22:04:28.531724  3503 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([0.], dtype=float32), gc=, dc=[, device_type: 1], engine=u'')
{u'X': }
{u'X': device_type: 1
}
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([[[[-0.25521252],
         [-0.25521252],
         [-0.25521252],
         [-0.25521252]],

        [[-0.25521252],
         [-0.25521252],
         [-0.25521252],
         [-0.25521252]],

        [[-0.25521252],
         [-0.25521252],
         [-0.25521252],
         [-0.25521252]]],


       [[[-0.25521252],
         [-0.25521252],
         [ 0.37402993],
         [-0.25521252]],

        [[-0.25521252],
         [-0.25521252],
         [-0.25521252],
         [-0.25521252]],

        [[-0.25521252],
         [-0.25521252],
         [-0.25521252],
         [-0.25521252]]],


       [[[-0.25521252],
         [-0.25521252],
         [ 0.6883273 ],
         [-0.25521252]],

        [[-0.25521252],
         [-0.25521252],
         [-0.25521252],
         [-0.25521252]],

        [[-0.25521252],
         [ 0.86089224],
         [-0.25521252],
         [-0.25521252]]]], dtype=float32), gc=device_type: 1, dc=[, device_type: 1], engine=u'')
{u'X': }
{u'X': device_type: 1
}
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([[-0.793503  , -0.793503  , -0.793503  ],
       [-0.49327314, -0.793503  , -0.793503  ],
       [-0.793503  , -0.793503  , -0.793503  ],
       [-0.29144055, -0.793503  , -0.793503  ],
       [-0.793503  ,  0.07806086, -0.5510364 ]], dtype=float32), gc=device_type: 1, dc=[, device_type: 1], engine=u'CUDNN')
{u'X': }
I0702 22:04:28.761914  3503 operator.cc:169] Engine CUDNN is not available for operator Relu.
{u'X': device_type: 1
}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 671, in evaluate_test_data
    result = self.execute(data, collect=True)
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 586, in execute
    result = self.test_runner(data, run)
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/executors.py", line 58, in default_new_style_executor
    return function(data)
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 582, in run
    return test(*args, **kwargs)
  File "caffe2/python/operator_test/relu_op_test.py", line 19, in test_relu
    engine=st.sampled_from(["", "CUDNN"]),
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 524, in test
    result = self.test(*args, **kwargs)
  File "caffe2/python/operator_test/relu_op_test.py", line 26, in test_relu
    self.assertDeviceChecks(dc, op, [X], [0])
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/hypothesis_test_util.py", line 350, in assertDeviceChecks
    dc.CheckSimple(op, inputs, outputs_to_check, input_device_options)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/device_checker.py", line 49, in CheckSimple
    workspace.RunOperatorOnce(op)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 165, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
RuntimeError: [enforce fail at context_gpu.h:100] status == CUDNN_STATUS_SUCCESS. 4 vs 0. , Error at: /home/tets/pytorch/caffe2/core/context_gpu.h:100: CUDNN_STATUS_INTERNAL_ERROR Error from operator: 
input: "X" output: "Y" name: "" type: "Relu" device_option { device_type: 1 } engine: "CUDNN"
```

I compiled denspose with no pb, and passed the detectron checks:
```
python2 $DENSEPOSE/detectron/tests/test_spatial_narrow_as_op.py
No handlers could be found for logger "caffe2.python.net_drawer"
net_drawer will not run correctly. Please install the correct dependencies.
E0702 22:22:49.913838  3731 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0702 22:22:49.913887  3731 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0702 22:22:49.913918  3731 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
...
----------------------------------------------------------------------
Ran 3 tests in 0.932s

OK
```

```

 python2 $DENSEPOSE/detectron/tests/test_zero_even_op.py
E0702 22:24:07.535202  3750 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0702 22:24:07.535217  3750 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0702 22:24:07.535226  3750 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
............
----------------------------------------------------------------------
Ran 12 tests in 0.136s

OK
```

But when running the infer_simple.py command, I got the below cryptic error message.

```
~/densepose$ python2 tools/infer_simple.py     --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml     --output-dir DensePoseData/infer_out/     --image-ext jpg     --wts https://s3.amazonaws.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl     DensePoseData/demo_data/20170716_101313.jpg
/home/tets/.local/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
E0702 21:59:20.453374  3391 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0702 21:59:20.453388  3391 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0702 21:59:20.453392  3391 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  51: Loading weights from: /tmp/detectron-download-cache/DensePose_ResNet101_FPN_s1x-e2e.pkl
I0702 21:59:21.176241  3391 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.000106374 secs
I0702 21:59:21.185215  3391 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 8.9347e-05 secs
I0702 21:59:21.186816  3391 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 1.1866e-05 secs
INFO infer_simple.py: 103: Processing DensePoseData/demo_data/20170716_101313.jpg -> DensePoseData/infer_out/20170716_101313.jpg.pdf
I0702 21:59:21.589475  3391 net_async_base.cc:435] Using specified CPU pool size: 4; NUMA node id: -1
I0702 21:59:21.589490  3391 net_async_base.cc:440] Created new CPU pool, size: 4; NUMA node id: -1
E0702 21:59:23.285727  3413 net_async_base.cc:368] [enforce fail at context_gpu.h:100] status == CUDNN_STATUS_SUCCESS. 4 vs 0. , Error at: /home/tets/pytorch/caffe2/core/context_gpu.h:100: CUDNN_STATUS_INTERNAL_ERROR Error from operator: 
input: "gpu_0/data" input: "gpu_0/conv1_w" output: "gpu_0/conv1" name: "" type: "Conv" arg { name: "kernel" i: 7 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 3 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN",  op Conv
WARNING workspace.py: 185: Original python traceback for operator `0` in network `generalized_rcnn` in exception above (most recent call last):
WARNING workspace.py: 190:   File "tools/infer_simple.py", line 140, in <module>
WARNING workspace.py: 190:   File "tools/infer_simple.py", line 91, in main
WARNING workspace.py: 190:   File "/home/tets/densepose/detectron/core/test_engine.py", line 334, in initialize_model_from_cfg
WARNING workspace.py: 190:   File "/home/tets/densepose/detectron/modeling/model_builder.py", line 119, in create
WARNING workspace.py: 190:   File "/home/tets/densepose/detectron/modeling/model_builder.py", line 84, in generalized_rcnn
WARNING workspace.py: 190:   File "/home/tets/densepose/detectron/modeling/model_builder.py", line 233, in build_generic_detection_model
WARNING workspace.py: 190:   File "/home/tets/densepose/detectron/modeling/optimizer.py", line 46, in build_data_parallel_model
WARNING workspace.py: 190:   File "/home/tets/densepose/detectron/modeling/model_builder.py", line 165, in _single_gpu_build_func
WARNING workspace.py: 190:   File "/home/tets/densepose/detectron/modeling/FPN.py", line 55, in add_fpn_ResNet101_conv5_body
WARNING workspace.py: 190:   File "/home/tets/densepose/detectron/modeling/FPN.py", line 96, in add_fpn_onto_conv_body
WARNING workspace.py: 190:   File "/home/tets/densepose/detectron/modeling/ResNet.py", line 40, in add_ResNet101_conv5_body
WARNING workspace.py: 190:   File "/home/tets/densepose/detectron/modeling/ResNet.py", line 90, in add_ResNet_convX_body
WARNING workspace.py: 190:   File "/home/tets/densepose/detectron/modeling/ResNet.py", line 243, in basic_bn_stem
WARNING workspace.py: 190:   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/cnn.py", line 97, in Conv
WARNING workspace.py: 190:   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/brew.py", line 107, in scope_wrapper
WARNING workspace.py: 190:   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/helpers/conv.py", line 186, in conv
WARNING workspace.py: 190:   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/helpers/conv.py", line 139, in _ConvBase
Traceback (most recent call last):
  File "tools/infer_simple.py", line 140, in <module>
    main(args)
  File "tools/infer_simple.py", line 109, in main
    model, im, None, timers=timers
  File "/home/tets/densepose/detectron/core/test.py", line 58, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/home/tets/densepose/detectron/core/test.py", line 158, in im_detect_bbox
    workspace.RunNet(model.net.Proto().name)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 217, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at context_gpu.h:100] status == CUDNN_STATUS_SUCCESS. 4 vs 0. , Error at: /home/tets/pytorch/caffe2/core/context_gpu.h:100: CUDNN_STATUS_INTERNAL_ERROR Error from operator: 
input: "gpu_0/data" input: "gpu_0/conv1_w" output: "gpu_0/conv1" name: "" type: "Conv" arg { name: "kernel" i: 7 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 3 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
```

my NVIDIA setup for ref:
```
Mon Jul  2 22:20:18 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980 Ti  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   50C    P0    61W / 250W |    243MiB /  6077MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1141      G   /usr/lib/xorg/Xorg                            17MiB |
|    0      1447      G   /usr/lib/xorg/Xorg                           101MiB |
|    0      1917      G   /usr/bin/gnome-shell                          93MiB |
+-----------------------------------------------------------------------------+
```

**Comment by vkhalidov** [comment]
@Tetsujinfr just a guess - could this be similar to [this issue](https://stackoverflow.com/questions/47060565/tensorflow-only-works-under-root-after-drivers-update)?

**Comment by Tetsujinfr** [comment]
Thanks for your suggestion. I was so hopeful but it did not work unfortunately. Same error after adding my user to the nvidia-persistended list.

Any other suggestion?
I cannot make any sense of the error messages.

**Comment by Tetsujinfr** [comment]
I think it may be that the code cannot find CuDNN at runtime, but not sure on how to confirm that and not sure why that would be the case (my  libcudnn.so v6.0.21 is under /usr/local/cuda-8.0/lib64 and I have this path in my LD_LIBRARY_PATH env variable)

**Comment by vkhalidov** [comment]
You get CUDNN_STATUS_INTERNAL_ERROR with your code, which means cuDNN is found at runtime. You can try to disable cuDNN in Caffe2 and check that everything runs properly.
It looks like your issue arises from the particular combination of NVidia GPU, NVidia driver, CUDA and cuDNN. So if everything runs as expected without cuDNN, I would try different combinations of NVidia driver, CUDA and cuDNN or contact NVidia support to suggest a working combination for you GPU.

**Comment by Gorgrammer** [comment]
Hi, @Tetsujinfr , I met exactly the same error as yours, have you fixed it now? could you share the way to solve this problem? Thanks!

**Comment by Tetsujinfr** [comment]
Still trying to figure out where this is coming from. Maybe the drivers.Gorgrammer, which GPU do you have on your end, and which driver version?

**Comment by Gorgrammer** [comment]
I have a TITAN X (Pascal) and a Driver Version 390.48, while I think probably this problem has something to do with the engine. When I run relu_op_test.py with engine="CAFFE", it seems ok (it will print "OK" instead of an error). I hope this would help.  

And now I am trying to find where to change the engine when running the detectron train.py, I wonder if you know which script or file contains the code below:

input: "gpu_0/data" input: "gpu_0/conv1_w" output: "gpu_0/conv1" name: "" type: "Conv" arg { name: "kernel" i: 7 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 3 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"

**Comment by bartengine27** [comment]
@Gorgrammer did you compile caffe2 with cudnn support?

**Comment by Gorgrammer** [comment]
@bartengine27  About this problem, I did use cudnn7 together with cuda9.1, then a mate told me that caffe2 did not support cuda9.1 very well, and it's cuda8.0 or cuda9.0 that should be used here; so I tried cuda8.0 (with cudnn7) and it worked.

**Comment by Tetsujinfr** [comment]
Did you compile caffe or did you ise the Conda binaries?
Asking cause I bought a new HDD to reinstall my ubuntu16.04 setup from scratch, with Cuda9.0 and Cudnn 7.0, but after installing with conda, the GPU acceleration does not work.
So I will probably install all from scratch again and compile Caffe2 from source (longer but it should work better I hope).

**Comment by Gorgrammer** [comment]
I built it from source, and you can find the path of cuda and cudnn you are using in the output of cmake command.

**Comment by Tetsujinfr** [comment]
I managed to get it installed after quite a lot of troubles. I did re-install from a clean Ubuntu install. Did install Cuda 8.0 with Cudnn 7. I did compile caffe2 from source and used miniconda for the python and other dependency stack. My caffe2 installed libraries are under usr/local/lib which I did put in the LD_LIBRARY_PATH and my caffe2 modules are in the pytorch/build folder which I did add to my PYTHONPATH. I had to fix a small issue with ATen headers which were not installed properly (this will likely be fixed with newer versions of caffe2 code), I did mention the details under issue #97.
Closing this issue consequently.
